name: release
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Clone Indigo
        run: |
          git clone https://github.com/bluesky-social/indigo.git
      - uses: actions/setup-go@v6
        with:
          go-version-file: indigo/go.mod
          check-latest: true
      - name: Build Tap Binary
        run: |
          cd indigo && git switch $TAG && go build -o tap ./cmd/tap
        env:
          TAG: ${{ github.ref_name }}
      - name: Create Archive and Checksum
        run: |
          cd indigo
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#tap-}"
          OS_NAME=$(echo "${{ matrix.os }}" | cut -d'-' -f1)
          if [ "$OS_NAME" = "ubuntu" ]; then
            if [[ "${{ matrix.os }}" == *"arm"* ]]; then
              ARCH="arm64"
            else
              ARCH="amd64"
            fi
            PLATFORM="linux-${ARCH}"
          else
            ARCH="arm64"
            PLATFORM="darwin-${ARCH}"
          fi
          ARCHIVE_NAME="tap-${VERSION}-${PLATFORM}.tar.gz"
          tar -czf "../${ARCHIVE_NAME}" tap
          cd ..
          sha256sum "${ARCHIVE_NAME}" > "${ARCHIVE_NAME}.sha256"
      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#tap-}"
            OS_NAME=$(echo "${{ matrix.os }}" | cut -d'-' -f1)
            if [ "$OS_NAME" = "ubuntu" ]; then
              if [[ "${{ matrix.os }}" == *"arm"* ]]; then
                ARCH="arm64"
              else
                ARCH="amd64"
              fi
              PLATFORM="linux-${ARCH}"
            else
              ARCH="arm64"
              PLATFORM="darwin-${ARCH}"
            f
            tap-${VERSION}-${PLATFORM}.tar.gz
            tap-${VERSION}-${PLATFORM}.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
